name: vivatech
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  path_provider: ^2.0.15
  flutter_pdfview: ^1.3.1
  aspose_words_cloud: ^23.4.0
  file_picker: ^5.3.1
  http: ^0.13.4
  path: ^1.8.0
  permission_handler: ^8.1.6
  cv: ^0.2.12
  provider: ^6.0.5
  qr_flutter: ^4.0.1
  qr_code_scanner: ^1.0.1
  carousel_slider: ^4.2.1
  animated_text_kit: ^4.2.2
  ar_flutter_plugin: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.0.1+1
  flutter_launcher_icons: ^0.13.1
  flutter_shake_animated: ^0.0.5
  onboarding_animation: any
  animated_text_kit: ^4.2.2



# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/background/
     - assets/icons/
     - assets/pages/
     - assets/images/
     - assets/pages/home/
     - assets/pages/games/
     - assets/pages/games/characters/
     - assets/pages/games/logic/
     - assets/pages/conferences/
     - assets/pages/conferences/FoodTech/
     - assets/pages/conferences/Cybersecurity/
     - assets/pages/conferences/DeepTech/
     - assets/pages/conferences/Metaverse/
     - assets/pages/conferences/IA/
     - assets/pages/stands/
     - assets/pages/pass/
     - assets/pages/ar/
     - assets/pages/cv/
   
  fonts:
     - family: MuseoSans
       fonts:
         - asset: assets/fonts/MuseoSans-100.otf
           weight: 100
         - asset: assets/fonts/MuseoSans-300.otf
           weight: 300
         - asset: assets/fonts/MuseoSans-500.otf
           weight: 500
         - asset: assets/fonts/MuseoSans-700.otf
           weight: 700
         - asset: assets/fonts/MuseoSans-900.otf
           weight: 900



#custom splash screen
flutter_native_splash:
  image: assets/splashscreen/icon.png
  background_image: assets/background/bg-gradient-vivatech.png
  ios: true
  android: true


#custom launch icon
flutter_launcher_icons:
  android: launcher_icon
  ios: true
  remove_alpha_ios: true
  image_path: assets/icons/icon.png